name: save-logs
description: "Save debug logs"

runs:
  using: composite
  steps:
    - name: Fix log permissions
      run: |
        sudo chown $USER /tmp/go-oscal-*.log || echo ""
      shell: bash

    - uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4.3.6
      with:
        name: debug-log
        path: /tmp/go-oscal-*.log