name: setup-go
description: "Setup Go binary and caching"

runs:
  using: composite
  steps:
    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
      with:
        go-version-file: './go.mod'
        cache: true