name: setup-go
description: "Setup Go binary and caching"

runs:
  using: composite
  steps:
    - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version-file: './go.mod'
        cache: true