name: Create Issue on PR for OSCAL Version Updates

permissions:
  contents: read
  issues: write

on:
  pull_request:
    paths:
      - 'update/oscal-version.yaml'

jobs:
  createIssue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const title = `PR #${context.payload.pull_request.number} OSCAL Version Update`;
            const body = `A new OSCAL version has been released. Please review the changes https://github.com/usnistgov/OSCAL/releases, and update the version in the repository. See [upgrading-oscal-version](https://github.com/defenseunicorns/go-oscal/blob/main/docs/upgrading-oscal-version.md). PR #${context.payload.pull_request.number}`;
            const projectID = '12';

            // query existing issues with the same title
            const {
              data: { items: issues }
            } = await github.rest.search.issuesAndPullRequests({
              q: `repo:defenseunicorns/go-oscal is:issue is:open ${title} in:title`
            });

            // bail if the issue already exists
            if (issues.length > 0) {
              console.log('Issue already exists');
              return;
            }

            // create the issue
            github.rest.issues.create({
              owner: 'defenseunicorns',
              repo: 'go-oscal',
              title: title,
              body: body,
              labels: ['enhancement']
            });
