name: Publish go-oscal 

on:
  push:
    branches:
      - main

jobs:
  tag-new-version:
    name: Tag New Version
    permissions: 
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Create release tag
        id: tag
        uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee