name: Publish go-oscal 

on:
  push:
    branches:
      - main

permissions: 
  contents: read

jobs:
  tag-new-version:
    name: Tag New Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Create release tag
        id: tag
        uses: googleapis/release-please-action@f3969c04a4ec81d7a9aa4010d84ae6a7602f86a7