name: Publish go-oscal 

on:
  push:
    branches:
      - main

permissions: 
  contents: read

jobs:
  tag-new-version:
    name: Tag New Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Create release tag
        id: tag
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5