name: Scan CVEs
on:
  schedule:
    - cron: "0 10 * * *"
  pull_request:
    paths:
      - "go.mod"
      - "go.sum"

jobs:
  scan-cves:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Scan Dependencies for CVEs
        uses: anchore/scan-action@v3
        with:
          path: "."
          fail-build: true
          severity-cutoff: low
