name: Issue Triage Label

on:
  issues:
    types: [opened, reopened]

permissions:
  issues: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Add triage label
      uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
      with:
        script: |
          const issueNumber = context.issue.number;
          github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber,
            labels: ['triage']
          });
